## Edtech Program Management and Analytics Portfolio

## Project Objective : 
    Develop an end to end program management solution for an online university by using Python, Excel, Power BI and Jira to improve student success, monitor KPIs and support data-driven decision making

## Program offered

    -BBA
    -BCA
    -M.Com
    -MBA
    -B.Com

## Student Lifecycle
 1. Admission
 2. Fee Payment
 3. LMS Activation 
 4. Orientation
 5. Semester 1
 6. Semester 2
 7. Semester 3
 8. Semester 4
 9. Semester 5
 10. Semester 6
 11. Graduation

## Issues Categories
    -LMS Issue
    -Fee Payment
    -Academic Queries
    -Assignment Issues
    -Examination Queries
    -Attendance Issue
    -Login Problems
    -Course Access
    -Tecnical Support
    -Certificate Request

## Key Perfomance Indicator (KPIs)
### Academic KPIs
    -Student Attendance %
    -Student Engagement
    -Assignment Submission Rate
    -Exam Participation Rate
    -Course Completion %
    -On-Time Course Completion
    -Pass Percentage
    -Students without Backlogs

### Operational KPIs
    -Average Ticket Resolution Time
    -SLA Compliance %
    -Student Satisfaction (CSAT)
    -Escalation Count
    -Active Students
    -Dropout Rate

In [2]:
##import libraries
import pandas as pd
import numpy as np
from faker import Faker
import random
from datetime import datetime,timedelta

##pandas → Create the DataFrame
##numpy → Generate random numbers
##faker → Generate fake names and cities
##random → Randomly choose values like Program and Gender
##datetime → Generate enrollment dates

In [3]:
excel_path = r"C:\Users\User\OneDrive\Desktop\EdTech_Program_Management_Database.xlsx"

In [4]:
## function to save the dataset in excel
def save_to_excel (df, sheet_name):
    with pd.ExcelWriter(
        excel_path ,
        engine = "openpyxl",
        mode = "a",
        if_sheet_exists = "replace",
    ) as writer:
        df.to_excel(writer,sheet_name = sheet_name, index = False)
    print(f"{sheet_name} saved successfully")
    
    #df = What data should I save?
    #sheet_name = Where should I save it?
    #save_to_excel = function name

In [5]:
fake = Faker('en_IN')

## Student_Master_Data

In [8]:
num_students = 500
students = []

for i in range(1, num_students + 1):

    program = random.choice(["MBA", "BBA", "B.Com", "BCA", "M.Com"])

    if program in ["BBA", "B.Com", "BCA"]:
        semester = random.randint(1, 6)
    else:
        semester = random.randint(1, 4)

    student = {
        "Student_ID": f"STU{i:04}",
        "Student_Name": fake.name(),
        "Gender": random.choice(["Male", "Female"]),
        "Age": random.randint(17, 70),
        "City": fake.city(),
        "Program": program,
        "Batch": random.choice(["Jan 2025", "July 2025"]),
        "Semester": semester,
        "Enrollment_Date": fake.date_between(start_date="-2y", end_date="today"),
        "Fee_status": random.choice(["Paid", "Pending"]),
        "Attendance": random.randint(60, 100),
        "Assignment_Submission": random.randint(50, 100),
        "Course_Completion": random.randint(0, 100),
        "Risk_level": random.choice(["Low", "Medium", "High"])
    }

    students.append(student)

student_df = pd.DataFrame(students)

In [9]:
#student_df = pd.DataFrame(students)
#It converts the list of dictionaries into a table.

In [7]:
student_df.head()

,Student_ID,Student_Name,Gender,Age,City,Program,Batch,Semester,Enrollment_Date,Fee_status,Attendance,Assignment_Submission,Course_Completion,Risk_level
0,STU0001,Arya Tella,Male,60,Ludhiana,BBA,July 2025,3,2026-02-24,Paid,79,72,73,Low
1,STU0002,Hamsini Date,Female,37,Loni,M.Com,July 2025,3,2025-03-24,Paid,85,71,88,Low
2,STU0003,Avni Suresh,Female,67,Pondicherry,B.Com,Jan 2025,1,2026-05-26,Paid,70,84,1,Low
3,STU0004,Vasana Chakrabarti,Female,67,Gurgaon,M.Com,July 2025,2,2024-11-08,Pending,69,73,7,High
4,STU0005,Brijesh Mani,Female,17,Kolhapur,MBA,July 2025,4,2024-11-14,Pending,88,87,24,High

In [10]:
student_df.shape
#len(students)

(500, 14)

In [11]:
save_to_excel(student_df , "Student_Master")

Student_Master saved successfully

## Faculty_Master_Data

In [10]:
departments = [
    "Management",
    "Computer Science",
    "Data Science",
    "Commerce",
    "Finance",
    "Human Resource",
    "Marketing",
    "Operations"
    ]          

qualifications = [
    "MBA",
    "M.Tech",
    "M.Sc",
    "M.Com",
    "Phd",
    "MCA"
    ]

subjects = [
    "Financial Accounting",
    "Business Economics",
    "Marketing Management",
    "Human Resource Management",
    "Business Communication",
    "Financial Management",
    "Business Analytics",
    "Organizational Behavior",
    "Management Principles",
    "Computer Fundamentals",
    "Programming",
    "Database Management",
    "Web Development",
    "Data Structures",
    "Computer Networks"
]

In [11]:
## Faculty_Master

num_faculties = 100
faculties = []
career_start_age = 23

for i in range (1, num_faculties+1):
    age = random.randint(25,60)
    #print(f"faculty {i}") 
    faculty = {
        "faculty_Id" : f"FAC{i:03}",
        "faculty_name" : fake.name(),
        "Gender" : random.choice(["Male","Female"]),
        "Age" : age,
        "Email" : fake.email(),
        "Phone_Number": "+91" + str(random.randint(6, 9)) + "".join([str(random.randint(0, 9)) for _ in range(9)]),
        "Department" : random.choice(departments),
        "Subject" : random.choice(subjects),
        "Qualification" : random.choice(qualifications),
        "Experience_Years" : random.randint(1, age - career_start_age),
        "Joining_Date" : fake.date_between (start_date="-15y",end_date="today"),
        "Employment_Type" : random.choice(["Full-Time","Part-Time","Visiting-Faculty"]),
        "Faculty_Rating"  : round(random.uniform(3.0,5.0),1),
        "City"            : fake.city()
    }
    
    faculties.append(faculty) 
    
faculty_df = pd.DataFrame(faculties)

In [12]:
faculty_df.head()

,faculty_Id,faculty_name,Gender,Age,Email,Phone_Number,Department,Subject,Qualification,Experience_Years,Joining_Date,Employment_Type,Faculty_Rating,City
0,FAC001,Girish Nagy,Female,53,pathakagastya@example.net,+916421842245,Finance,Web Development,MCA,17,2020-12-02,Visiting-Faculty,4.2,Gandhinagar
1,FAC002,Omisha Nagy,Male,36,mohini37@example.net,+916352217926,Finance,Financial Accounting,MBA,9,2021-11-03,Full-Time,3.2,Imphal
2,FAC003,Rachit Krishnan,Male,42,rachitbrar@example.com,+919736899668,Finance,Programming,M.Com,19,2012-07-04,Visiting-Faculty,3.4,Nellore
3,FAC004,Yash Comar,Female,29,samarthbalay@example.com,+916734378020,Marketing,Business Communication,M.Tech,5,2013-06-06,Part-Time,4.9,Bulandshahr
4,FAC005,Gautami Memon,Female,58,mallicklakshmi@example.org,+919920913369,Commerce,Web Development,M.Tech,33,2024-12-20,Part-Time,4.9,Thoothukudi

In [13]:
faculty_df.shape

(100, 14)

In [14]:
save_to_excel(faculty_df, "Faculty_Master")

Faculty_Master saved successfully

## Course_Master_Data

In [15]:
programs = [
    "BBA",
    "BCA",
    "B.Com",
    "MBA",
    "M.Com"
    ]

courses_by_program = {
     "BBA" :
    [
        "Principles of Management",
        "Financial Accounting",
        "Business Economics",
        "Marketing Management",
        "Human Resource Management",
        "Business Communication"
     ],
    
    "BCA" : 
    [
        "Programming Fundamentals",
        "Database Management",
        "Data Structures",
        "Computer Networks",
        "Web Development",
        "Operating Systems"
    ],
    
    "B.Com" :
    [ 
        "Financial Accounting",
        "Business Economics",
        "Corporate Accounting",
        "Business Law",
        "Income Tax",
        "Cost Accounting"
    ],
    
    "MBA" : 
    [
         "Strategic Management",
        "Financial Management",
        "Marketing Management",
        "Human Resource Management",
        "Business Analytics",
        "Operations Management"
    ],

    "M.Com" :
    [
        "Advanced Accounting",
        "Financial Management",
        "Corporate Finance",
        "Business Research",
        "Advanced Economics",
        "Taxation"
    ]
}

program_semester ={
    "BCA" : 6,
    "BBA" : 6,
    "B.Com" : 6,
    "MBA" : 4,
    "M.Com" : 4
}

program_department = {
   "BBA" : "Management",
    "BCA": "Computer Science",
    "B.Com": "Commerce",
    "MBA": "Management",
    "M.Com": "Commerce"
}

course_types = [
    "Core",
    "Elective"
]

In [16]:
## Course_Master

num_courses = 30
courses = []

for i in range (1,num_courses+1):
     program = random.choice(programs)
     course_name = random.choice(courses_by_program[program])
    
     course = {
     "Course_ID" : f"COU{i:03}",
     "Program" : program,
     "Course_Name" : course_name,
     "Department" : program_department[program],
     "Semester" :random.randint(1,program_semester[program]),
     "Credits" : random.choice([3, 4]),
     "Course_Type" : random.choice(course_types),
     "Faculty_ID" : random.choice(faculty_df["faculty_Id"].tolist()),
     "Course_Duration_Months" : 4                                      #treating each semester as approximately 4 months of academic instruction.
     }
     courses.append(course)
course_df = pd.DataFrame(courses)

In [17]:
course_df.shape

(30, 9)

In [18]:
course_df.head()

,Course_ID,Program,Course_Name,Department,Semester,Credits,Course_Type,Faculty_ID,Course_Duration_Months
0,COU001,B.Com,Business Economics,Commerce,6,4,Elective,FAC075,4
1,COU002,M.Com,Advanced Accounting,Commerce,4,3,Elective,FAC064,4
2,COU003,MBA,Operations Management,Management,1,3,Core,FAC082,4
3,COU004,MBA,Marketing Management,Management,1,3,Core,FAC063,4
4,COU005,BBA,Principles of Management,Management,6,4,Core,FAC043,4

In [19]:
save_to_excel(course_df, "Course_Master")

Course_Master saved successfully

## Attendance_Master_Data

In [20]:
# ============================================================
# FINAL FACULTY SUBJECT COVERAGE + ATTENDANCE DATASET
# ============================================================

# 1. Get all unique subjects used across all programs
all_course_subjects = list(dict.fromkeys(
    subject
    for subject_list in courses_by_program.values()
    for subject in subject_list
))

print("Total unique subjects:", len(all_course_subjects))


# 2. Guarantee that every subject has at least one faculty
# First 25 faculty get one unique subject each

for i, subject in enumerate(all_course_subjects):
    faculty_df.loc[i, "Subject"] = subject


# Remaining faculty are distributed among valid course subjects
for i in range(len(all_course_subjects), len(faculty_df)):
    faculty_df.loc[i, "Subject"] = random.choice(all_course_subjects)


# 3. Validate Faculty coverage BEFORE Attendance generation

missing_subjects = (
    set(all_course_subjects)
    - set(faculty_df["Subject"])
)

print("Subjects without faculty:", missing_subjects)

if missing_subjects:
    raise ValueError(
        f"Faculty coverage incomplete: {missing_subjects}"
    )


# ============================================================
# 4. GENERATE SUBJECT-WISE ATTENDANCE
# ============================================================

attendance = []

for _, student in student_df.iterrows():

    student_id = student["Student_ID"]
    program = student["Program"]
    semester = student["Semester"]

    # Six valid subjects for the student's program
    valid_subjects = courses_by_program[program]

    for subject in valid_subjects:

        # Select only faculty teaching this exact subject
        faculty_options = faculty_df[
            faculty_df["Subject"] == subject
        ]

        faculty = faculty_options.sample(1).iloc[0]

        faculty_id = faculty["faculty_Id"]

        # Generate attendance figures
        classes_conducted = random.randint(30, 50)

        classes_attended = random.randint(
            15,
            classes_conducted
        )

        attendance_percentage = round(
            (classes_attended / classes_conducted) * 100,
            1
        )

        # Attendance status + risk
        if attendance_percentage >= 75:
            attendance_status = "Good"
            attendance_risk = "Low"

        elif attendance_percentage >= 60:
            attendance_status = "Average"
            attendance_risk = "Medium"

        else:
            attendance_status = "Poor"
            attendance_risk = "High"

        # Create attendance record
        attendance_record = {
            "Attendance_Id": f"ATT{len(attendance)+1:05}",
            "Student_ID": student_id,
            "Program": program,
            "Semester": semester,
            "Subject": subject,
            "Faculty_Id": faculty_id,
            "Classes_Conducted": classes_conducted,
            "Classes_Attended": classes_attended,
            "Attendance_Percentage": attendance_percentage,
            "Attendance_Status": attendance_status,
            "Attendance_Risk": attendance_risk
        }

        attendance.append(attendance_record)


# 5. Convert to DataFrame
attendance_df = pd.DataFrame(attendance)


# ============================================================
# 6. FINAL VALIDATION
# ============================================================

print("\n--- ATTENDANCE VALIDATION ---")

print("Attendance Shape:",
      attendance_df.shape)

print("Missing Faculty IDs:",
      attendance_df["Faculty_Id"].isna().sum())

print("Invalid Student IDs:",
      (~attendance_df["Student_ID"]
       .isin(student_df["Student_ID"])).sum())

print("Unique Students:",
      attendance_df["Student_ID"].nunique())

print("\nUnique subjects per student:")

print(
    attendance_df
    .groupby("Student_ID")["Subject"]
    .nunique()
    .value_counts()
)

Total unique subjects: 25
Subjects without faculty: set()

--- ATTENDANCE VALIDATION ---
Attendance Shape: (3000, 11)
Missing Faculty IDs: 0
Invalid Student IDs: 0
Unique Students: 500

Unique subjects per student:
Subject
6    500
Name: count, dtype: int64

In [21]:
attendance_df.shape

(3000, 11)

In [22]:
len(attendance)

3000

In [23]:
save_to_excel(attendance_df,"Attendance_Master")

Attendance_Master saved successfully

## Issue_Tracker

In [24]:
##Issue_Tracker
issue_categories = [
    "LMS Issue",
    "Fee Payment",
    "Academic Queries",
    "Assignment Issues",
    "Examination Queries",
    "Attendance Issue",
    "Login Problem",
    "Course Access ",
    "Certificate Request"
    "Admission Queries"
]

priorities = [
    "Low",
    "Medium",
    "High",
    "Critical"
]

ticket_statuses = [
    "Open",
    "In-Progress",
    "Resolved",
    "Closed",
    "Re-Opened"
]

assigned_team = [
    "Academic Team",
    "Student Service Team",
    "Finance Team",
    "Examination Team",
    "Sales Team",
    "Technical Team"
]

sla_days = {
    "Low": 5,
    "Medium": 3,
    "High": 2,
    "Critical": 1
}

In [25]:
num_issues = 3000
issues = []

In [26]:
for i in range(1,num_issues + 1):
    student = student_df.sample(1).iloc[0]
    program = student["Program"]
    semester = student["Semester"]
    issue_category = random.choice(issue_categories)
    priority = random.choice(priorities)
    ticket_status = random.choice(ticket_statuses)
    issue_description = "General student query"

    if issue_category in ["LMS Issue", "Login Problems", "Course Access"]:
        assigned_team = "Technical Support"
        
    elif issue_category in ["Fee Payment"]:
        assigned_team = "Finance Team"
        
    elif issue_category in ["Examination Queries"]:
        assigned_team = "Examination Team"
        
    elif issue_category in ["Academic Queries", "Assignment Issues"]:
        assigned_team = "Academic Team"
        
    elif issue_category in ["Certificate Request","Attendance Issue"]:
        assigned_team = "Student Service Team"
        
    elif issue_category == "Admission Queries":
        assigned_team = "Sales Team"
        
    issue_date = fake.date_between(start_date = "-1y",end_date= "today")
    
    if issue_category == "LMS Issue":
        issue_description = "Unable to access LMS"
        
    elif issue_category == "Fee Payment":
        issue_description = "Payment not reflecting in the student portal or LMS"
        
    elif issue_category == "Academic Queries":
        issue_description = "Student has an query related to course subject"
        
    elif issue_category == "Assignment Issues":
        issue_description = "Unable to submit assignment"

    elif issue_category == "Examination Queries":
        issue_description = "Student has a query regarding examination"

    elif issue_category == "Attendance Issue":
        issue_description = "Attendance record discrepancy"

    elif issue_category == "Login Problems":
        issue_description = "Unable to login to student portal"

    elif issue_category == "Course Access":
        issue_description = "Unable to access course content"

    elif issue_category == "Certificate Request":
        issue_description = "Student requested course certificate"

    elif issue_category == "Admission Queries":
        issue_description = "Student has an admission-related query"

    if ticket_status in ["Resolved", "Closed"]:
       resolution_tat = random.randint(1, 7)

       resolution_date = issue_date + pd.Timedelta(days=resolution_tat)
    
    else:
        resolution_tat = None
        resolution_date = None

    if resolution_tat is None:
       sla_status = "Pending"

    elif resolution_tat <= sla_days[priority]:
         sla_status = "Within SLA"

    else:
         sla_status = "SLA Breached"

    issue_record = {
        "Issue_Id" : f"ISS{i:04}",
        "Student_ID": student["Student_ID"],
        "Program": program,
        "Semester": semester,
        "Issue_Date": issue_date,
        "Issue_Category": issue_category,
        "Issue_Description": issue_description,
        "Priority": priority,
        "Assigned_Team": assigned_team,
        "Ticket_Status": ticket_status,
        "Resolution_Date": resolution_date,
        "Resolution_TAT_Days": resolution_tat,
        "SLA_Status": sla_status
    }
    issues.append(issue_record)
issue_df = pd.DataFrame(issues)

In [27]:
issue_df.shape

(3000, 13)

In [28]:
save_to_excel(issue_df, "Issue_Tracker")

Issue_Tracker saved successfully

## Assignment_Master_Data

In [29]:
#Assignment_Data

assignment_statuses = ["submitted","not submitted"]

In [30]:
num_assignments = 3000
assignments = []

In [31]:
for i, student in student_df.iterrows():

    student_id = student["Student_ID"]
    program = student["Program"]
    semester = student["Semester"]

    valid_subjects = courses_by_program[program]

    for subject in valid_subjects:

        assignment_status = random.choice(assignment_statuses)

        assignment_record = {
            "Assignment_Id": f"ASN{len(assignments)+1:05}",
            "Student_ID": student_id,
            "Program": program,
            "Semester": semester,
            "Subject": subject,
            "Assignment_Status": assignment_status
        }

        assignments.append(assignment_record)

In [32]:
assignment_df = pd.DataFrame(assignments)

In [33]:
save_to_excel(assignment_df, "Assignment_Master")

Assignment_Master saved successfully

## Exam_Master_Data

In [34]:
exam_results = []

In [35]:
# FINAL EXAM RESULT DATASET

exam_results = []

for i, student in student_df.iterrows():

    student_id = student["Student_ID"]
    program = student["Program"]
    semester = student["Semester"]

    valid_subjects = courses_by_program[program]

    # Give each student an overall academic performance level
    performance_level = random.choices(
        ["High", "Average", "Low"],
        weights=[20, 50, 30],
        k=1
    )[0]

    for subject in valid_subjects:

        # Generate marks based on student's performance level
        if performance_level == "High":
            marks = random.randint(65, 100)

        elif performance_level == "Average":
            marks = random.randint(45, 80)

        else:
            marks = random.randint(25, 60)

        # Grade logic
        if marks >= 90:
            grade = "A+"
        elif marks >= 80:
            grade = "A"
        elif marks >= 70:
            grade = "B+"
        elif marks >= 60:
            grade = "B"
        elif marks >= 50:
            grade = "C+"
        elif marks >= 40:
            grade = "C"
        else:
            grade = "F"

        # Subject-level result
        if marks >= 40:
            result_status = "Pass"
        else:
            result_status = "Fail"

        exam_record = {
            "Exam_Result_ID": f"EXM{len(exam_results)+1:05}",
            "Student_ID": student_id,
            "Program": program,
            "Semester": semester,
            "Subject": subject,
            "Marks": marks,
            "Grade": grade,
            "Result_Status": result_status
        }

        exam_results.append(exam_record)

exam_result_df = pd.DataFrame(exam_results)

In [36]:
exam_result_df = pd.DataFrame(exam_results)

In [37]:
save_to_excel(exam_result_df, "Exam_Master_Data")

Exam_Master_Data saved successfully

In [38]:
exam_result_df.shape

(3000, 8)

## Final_Results_Data

In [100]:
# FINAL RESULT DATASET

final_results = []

for student_id, student_data in exam_result_df.groupby("Student_ID"):

    program = student_data["Program"].iloc[0]
    semester = student_data["Semester"].iloc[0]

    # Calculate overall marks
    total_marks = student_data["Marks"].sum()
    average_marks = round(student_data["Marks"].mean(), 1)

    # Student passes only if all subjects are passed
    if "Fail" in student_data["Result_Status"].values:
        final_result = "Fail"
    else:
        final_result = "Pass"

    # Final grade based on average marks
    if average_marks >= 90:
        final_grade = "A+"
    elif average_marks >= 80:
        final_grade = "A"
    elif average_marks >= 70:
        final_grade = "B+"
    elif average_marks >= 60:
        final_grade = "B"
    elif average_marks >= 50:
        final_grade = "C+"
    elif average_marks >= 40:
        final_grade = "D"
    else:
        final_grade = "F"

    final_record = {
        "Student_ID": student_id,
        "Program": program,
        "Semester": semester,
        "Total_Marks": total_marks,
        "Average_Marks": average_marks,
        "Final_Grade": final_grade,
        "Final_Result": final_result
    }

    final_results.append(final_record)

student_final_result_df = pd.DataFrame(final_results)

In [101]:
#student_final_result_df = student_final_result_df.drop_duplicates(subset=["Student_ID"],keep="first").reset_index(drop=True)

In [102]:
student_final_result_df.shape

(500, 7)

In [103]:
save_to_excel(student_final_result_df, "Result_Master_Data")

Result_Master_Data saved successfully

## Student_Feedback

In [43]:
#Student_Feedback
feedback_categories = [
    "Teaching Quality",
    "Course Content",
    "Faculty Support",
    "Learning Experience",
    "Assignment Workload",
    "Overall Satisfaction" 
    
]

In [44]:
num_feedback = 1500
feedback_results = []
#for i, student in student_df.iterrows():
for i in range(1, num_feedback + 1):
     student = student_df.sample(1).iloc[0]
     student_id = student["Student_ID"]
     program = student["Program"]
     semester = student["Semester"]


     feedback_category = random.choice(feedback_categories)
     rating = random.randint(1, 5)
    
     if rating >= 4:
        feedback_comment = "Student is satisfied with the learning experience"
     elif rating == 3:
        feedback_comment = "Student is moderately satisfied with the learning experience"
     else:
        feedback_comment = "Student reported areas that need improvement"
         
     feedback_record = {
        "Feedback_ID": f"FDB{i+1:04}",
        "Student_ID": student_id,
        "Program": program,
        "Semester": semester,
        "Feedback_Category": feedback_category,
        "Rating": rating,
        "Feedback_Comments": feedback_comment
     }
     feedback_results.append(feedback_record)

In [45]:
student_feedback_df = pd.DataFrame(feedback_results)

In [46]:
save_to_excel(student_feedback_df, "Student_Feedback_Master")

Student_Feedback_Master saved successfully

## Data_Validation

In [47]:
##Student_Master
print("Rows:", len(student_df))
print("Unique Student IDs:", student_df["Student_ID"].nunique())
print("Duplicate Student IDs:", student_df["Student_ID"].duplicated().sum())
print("Missing Student IDs:", student_df["Student_ID"].isna().sum())

Rows: 500
Unique Student IDs: 500
Duplicate Student IDs: 0
Missing Student IDs: 0

In [48]:
## Faculty_Master
print("Rows:", len(faculty_df))
print("Unique Faculty IDs:", faculty_df["faculty_Id"].nunique())
print("Duplicate Faculty IDs:", faculty_df["faculty_Id"].duplicated().sum())
print("Missing Faculty IDs:", faculty_df["faculty_Id"].isna().sum())

Rows: 100
Unique Faculty IDs: 100
Duplicate Faculty IDs: 0
Missing Faculty IDs: 0

In [49]:
## Course_Master
print("Rows:", len(course_df))
print("Unique Course IDs:", course_df["Course_ID"].nunique())
print("Duplicate Course IDs:", course_df["Course_ID"].duplicated().sum())
print("Missing Course IDs:", course_df["Course_ID"].isna().sum())

Rows: 30
Unique Course IDs: 30
Duplicate Course IDs: 0
Missing Course IDs: 0

In [50]:
##Student IDs across Attendance datasets
student_ids = set(student_df["Student_ID"])

attendance_student_ids = set(attendance_df["Student_ID"])

invalid_attendance_ids = attendance_student_ids - student_ids

print("Invalid Student IDs:", len(invalid_attendance_ids))
print("Invalid IDs:", invalid_attendance_ids)

##Faculty IDs across Attendance datasets
faculty_ids = set(faculty_df["faculty_Id"])

attendance_faculty_ids = set(attendance_df["Faculty_Id"])

invalid_faculty_ids = attendance_faculty_ids - faculty_ids

print("Invalid Faculty IDs:", len(invalid_faculty_ids))
print("Invalid IDs:", invalid_faculty_ids)

 ## faculty association with subject
faculty_subject_check = attendance_df.merge(
    faculty_df[["faculty_Id", "Subject"]],
    left_on="Faculty_Id",
    right_on="faculty_Id",
    suffixes=("_Attendance", "_Faculty")
)

invalid_faculty_subject = faculty_subject_check[
    faculty_subject_check["Subject_Attendance"] !=
    faculty_subject_check["Subject_Faculty"]
]

print("Faculty-Subject mismatches:", len(invalid_faculty_subject))

Invalid Student IDs: 0
Invalid IDs: set()
Invalid Faculty IDs: 0
Invalid IDs: set()
Faculty-Subject mismatches: 0

In [51]:
##Issue_Tracker
issue_student_ids = set(issue_df["Student_ID"])

invalid_issue_ids = issue_student_ids - student_ids

print("Invalid Student IDs:", len(invalid_issue_ids))
print("Invalid IDs:", invalid_issue_ids)

Invalid Student IDs: 0
Invalid IDs: set()

In [52]:
##Assignments
## student_ID Mapping
assignment_student_ids = set(assignment_df["Student_ID"])

invalid_assignment_ids = assignment_student_ids - student_ids

print("Invalid Student IDs:", len(invalid_assignment_ids))
print("Invalid IDs:", invalid_assignment_ids)

##course_by_program Mapping

invalid_assignments = []

for _, row in assignment_df.iterrows():
    valid_subjects = courses_by_program[row["Program"]]

    if row["Subject"] not in valid_subjects:
        invalid_assignments.append(row)

print("Invalid Assignment Subjects:", len(invalid_assignments))

## count_map

assignment_subject_count = assignment_df.groupby("Student_ID")["Subject"].count()

print(assignment_subject_count.value_counts())

##all_different sub
assignment_unique_subject_count = assignment_df.groupby("Student_ID")["Subject"].nunique()

print(assignment_unique_subject_count.value_counts())

Invalid Student IDs: 0
Invalid IDs: set()
Invalid Assignment Subjects: 0
Subject
6    500
Name: count, dtype: int64
Subject
6    500
Name: count, dtype: int64

In [53]:
##Exam_Result
##Student_Id Mapping
exam_student_ids = set(exam_result_df["Student_ID"])

invalid_exam_ids = exam_student_ids - student_ids

print("Invalid Student IDs:", len(invalid_exam_ids))
print("Invalid IDs:", invalid_exam_ids)

##Course_by_program Mapping
invalid_exam_subjects = []

for _, row in exam_result_df.iterrows():
    valid_subjects = courses_by_program[row["Program"]]

    if row["Subject"] not in valid_subjects:
        invalid_exam_subjects.append(row)

print("Invalid Exam Subjects:", len(invalid_exam_subjects))

Invalid Student IDs: 0
Invalid IDs: set()
Invalid Exam Subjects: 0

In [54]:
##Final_result
final_student_ids = set(student_final_result_df["Student_ID"])

invalid_final_ids = final_student_ids - student_ids

print("Invalid Student IDs:", len(invalid_final_ids))
print("Invalid IDs:", invalid_final_ids)

Invalid Student IDs: 0
Invalid IDs: set()

In [55]:
##Feedback
feedback_student_ids = set(student_feedback_df["Student_ID"])

invalid_feedback_ids = feedback_student_ids - student_ids

print("Invalid Student IDs:", len(invalid_feedback_ids))
print("Invalid IDs:", invalid_feedback_ids)

Invalid Student IDs: 0
Invalid IDs: set()

In [56]:
invalid_exam_subjects[:10]

[]

In [57]:
#invalid_exam_subjects_df = pd.DataFrame(invalid_exam_subjects)

#invalid_exam_subjects_df[["Student_ID", "Program", "Semester", "Subject"]].head(20)

In [58]:
exam_result_df.shape

(3000, 8)

In [59]:
exam_result_df[exam_result_df["Student_ID"] == "STU0001"][["Student_ID", "Program", "Subject", "Marks"]]

  Student_ID Program                    Subject  Marks
0    STU0001     BBA   Principles of Management     45
1    STU0001     BBA       Financial Accounting     73
2    STU0001     BBA         Business Economics     75
3    STU0001     BBA       Marketing Management     55
4    STU0001     BBA  Human Resource Management     69
5    STU0001     BBA     Business Communication     46

In [60]:
exam_subject_count = exam_result_df.groupby("Student_ID")["Subject"].count()

print(exam_subject_count.value_counts())

Subject
6    500
Name: count, dtype: int64

In [61]:
exam_unique_subject_count = exam_result_df.groupby("Student_ID")["Subject"].nunique()

print(exam_unique_subject_count.value_counts())

Subject
6    500
Name: count, dtype: int64

In [62]:
##Attendance Validation

print("Attendance records:", len(attendance_df))
print("Minimum Attendance:", attendance_df["Attendance_Percentage"].min())
print("Maximum Attendance:", attendance_df["Attendance_Percentage"].max())
print("Missing Attendance:", attendance_df["Attendance_Percentage"].isna().sum())
invalid_attendance_status = attendance_df[
    (
        (attendance_df["Attendance_Percentage"] >= 75) &
        (attendance_df["Attendance_Status"] != "Good")
    )
    |
    (
        (attendance_df["Attendance_Percentage"] >= 60) &
        (attendance_df["Attendance_Percentage"] < 75) &
        (attendance_df["Attendance_Status"] != "Average")
    )
    |
    (
        (attendance_df["Attendance_Percentage"] < 60) &
        (attendance_df["Attendance_Status"] != "Poor")
    )
]

print("Invalid Attendance Status:", len(invalid_attendance_status))

Attendance records: 3000
Minimum Attendance: 30.0
Maximum Attendance: 100.0
Missing Attendance: 0
Invalid Attendance Status: 0

In [63]:
attendance_subject_count = attendance_df.groupby("Student_ID")["Subject"].count()

print(attendance_subject_count.value_counts())

Subject
6    500
Name: count, dtype: int64

In [64]:
attendance_unique_subject_count = attendance_df.groupby("Student_ID")["Subject"].nunique()

print(attendance_unique_subject_count.value_counts())

Subject
6    500
Name: count, dtype: int64

In [65]:
#Faculty subject relationship
faculty_subject_check = attendance_df.merge(
    faculty_df[["faculty_Id", "Subject"]],
    left_on="Faculty_Id",
    right_on="faculty_Id",
    suffixes=("_Attendance", "_Faculty")
)

invalid_faculty_subject = faculty_subject_check[
    faculty_subject_check["Subject_Attendance"] !=
    faculty_subject_check["Subject_Faculty"]
]

print("Faculty-Subject mismatches:", len(invalid_faculty_subject))

Faculty-Subject mismatches: 0

In [66]:
## Issue Tracker
print("Issue records:", len(issue_df))
print("Duplicate Issue IDs:", issue_df["Issue_Id"].duplicated().sum())
print("Missing Issue IDs:", issue_df["Issue_Id"].isna().sum())

Issue records: 3000
Duplicate Issue IDs: 0
Missing Issue IDs: 0

In [67]:
invalid_resolution = issue_df[
    issue_df["Ticket_Status"].isin(["Resolved", "Closed"]) &
    issue_df["Resolution_Date"].isna()
]

print("Resolved/Closed tickets without resolution date:", len(invalid_resolution))

Resolved/Closed tickets without resolution date: 0

In [68]:
invalid_pending_resolution = issue_df[
    ~issue_df["Ticket_Status"].isin(["Resolved", "Closed"]) &
    issue_df["Resolution_Date"].notna()
]

print("Unresolved tickets with resolution date:", len(invalid_pending_resolution))

Unresolved tickets with resolution date: 0

In [69]:
invalid_sla = issue_df[
    (
        (issue_df["Resolution_TAT_Days"].notna()) &
        (
            (
                (issue_df["Resolution_TAT_Days"] <= issue_df["Priority"].map(sla_days)) &
                (issue_df["SLA_Status"] != "Within SLA")
            )
            |
            (
                (issue_df["Resolution_TAT_Days"] > issue_df["Priority"].map(sla_days)) &
                (issue_df["SLA_Status"] != "SLA Breached")
            )
        )
    )
]

print("Invalid SLA records:", len(invalid_sla))

Invalid SLA records: 0

In [70]:
## Student_Final_Result
print("Final result records:", len(student_final_result_df))
print("Unique students:", student_final_result_df["Student_ID"].nunique())
print("Duplicate Student IDs:", student_final_result_df["Student_ID"].duplicated().sum())

Final result records: 500
Unique students: 500
Duplicate Student IDs: 0

In [71]:
exam_fail_check = exam_result_df.groupby("Student_ID")["Result_Status"].apply(
    lambda x: "Fail" if "Fail" in x.values else "Pass"
)

final_result_check = student_final_result_df.set_index("Student_ID")["Final_Result"]

comparison = exam_fail_check == final_result_check

print("Incorrect Final Results:", (~comparison).sum())

Incorrect Final Results: 0

In [72]:
## Student Feedback

print("Feedback records:", len(student_feedback_df))
print("Unique students:", student_feedback_df["Student_ID"].nunique())
print("Missing Student IDs:", student_feedback_df["Student_ID"].isna().sum())
print("Missing Ratings:", student_feedback_df["Rating"].isna().sum())

Feedback records: 1500
Unique students: 479
Missing Student IDs: 0
Missing Ratings: 0

In [73]:
print("Minimum Rating:", student_feedback_df["Rating"].min())
print("Maximum Rating:", student_feedback_df["Rating"].max())

Minimum Rating: 1
Maximum Rating: 5

In [74]:
invalid_feedback_ids = set(student_feedback_df["Student_ID"]) - set(student_df["Student_ID"])

print("Invalid Feedback Student IDs:", len(invalid_feedback_ids))

Invalid Feedback Student IDs: 0

In [75]:
all_students = set(student_df["Student_ID"])
feedback_students = set(student_feedback_df["Student_ID"])

missing_feedback_students = all_students - feedback_students

print("Students without feedback:", len(missing_feedback_students))

Students without feedback: 21

In [76]:
all_students = set(student_df["Student_ID"])
feedback_students = set(student_feedback_df["Student_ID"])

students_without_feedback = all_students - feedback_students

print(students_without_feedback)

{'STU0070', 'STU0402', 'STU0139', 'STU0307', 'STU0381', 'STU0026', 'STU0102', 'STU0291', 'STU0062', 'STU0384', 'STU0330', 'STU0229', 'STU0458', 'STU0219', 'STU0476', 'STU0144', 'STU0158', 'STU0282', 'STU0161', 'STU0368', 'STU0263'}

## Data Cleaning

In [77]:
print("Student Master")
print(student_df.isnull().sum())

print("\nFaculty Master")
print(faculty_df.isnull().sum())

print("\nCourse Master")
print(course_df.isnull().sum())

print("\nAttendance")
print(attendance_df.isnull().sum())

print("\nIssue Tracker")
print(issue_df.isnull().sum())

print("\nAssignment")
print(assignment_df.isnull().sum())

print("\nExam Result")
print(exam_result_df.isnull().sum())

print("\nStudent Final Result")
print(student_final_result_df.isnull().sum())

print("\nStudent Feedback")
print(student_feedback_df.isnull().sum())

Student Master
Student_ID               0
Student_Name             0
Gender                   0
Age                      0
City                     0
Program                  0
Batch                    0
Semester                 0
Enrollment_Date          0
Fee_status               0
Attendance               0
Assignment_Submission    0
Course_Completion        0
Risk_level               0
dtype: int64

Faculty Master
faculty_Id          0
faculty_name        0
Gender              0
Age                 0
Email               0
Phone_Number        0
Department          0
Subject             0
Qualification       0
Experience_Years    0
Joining_Date        0
Employment_Type     0
Faculty_Rating      0
City                0
dtype: int64

Course Master
Course_ID                 0
Program                   0
Course_Name               0
Department                0
Semester                  0
Credits                   0
Course_Type               0
Faculty_ID                0
Course_Duration_Months    0
dtype: int64

Attendance
Attendance_Id            0
Student_ID               0
Program                  0
Semester                 0
Subject                  0
Faculty_Id               0
Classes_Conducted        0
Classes_Attended         0
Attendance_Percentage    0
Attendance_Status        0
Attendance_Risk          0
dtype: int64

Issue Tracker
Issue_Id                  0
Student_ID                0
Program                   0
Semester                  0
Issue_Date                0
Issue_Category            0
Issue_Description         0
Priority                  0
Assigned_Team             0
Ticket_Status             0
Resolution_Date        1793
Resolution_TAT_Days    1793
SLA_Status                0
dtype: int64

Assignment
Assignment_Id        0
Student_ID           0
Program              0
Semester             0
Subject              0
Assignment_Status    0
dtype: int64

Exam Result
Exam_Result_ID    0
Student_ID        0
Program           0
Semester          0
Subject           0
Marks             0
Grade             0
Result_Status     0
dtype: int64

Student Final Result
Student_ID       0
Program          0
Semester         0
Total_Marks      0
Average_Marks    0
Final_Grade      0
Final_Result     0
dtype: int64

Student Feedback
Feedback_ID          0
Student_ID           0
Program              0
Semester             0
Feedback_Category    0
Rating               0
Feedback_Comments    0
dtype: int64

In [78]:
print("Attendance:", attendance_df.shape)
print("Issue Tracker:", issue_df.shape)

Attendance: (3000, 11)
Issue Tracker: (3000, 13)

In [79]:
print(attendance_df["Faculty_Id"].isna().sum())
print(attendance_df["Faculty_Id"].head(20))

0
0     FAC094
1     FAC078
2     FAC003
3     FAC031
4     FAC061
5     FAC093
6     FAC021
7     FAC018
8     FAC022
9     FAC045
10    FAC051
11    FAC025
12    FAC067
13    FAC064
14    FAC029
15    FAC042
16    FAC089
17    FAC092
18    FAC021
19    FAC044
Name: Faculty_Id, dtype: str

In [80]:
print(faculty_df["faculty_Id"].head())

0    FAC001
1    FAC002
2    FAC003
3    FAC004
4    FAC005
Name: faculty_Id, dtype: str

In [81]:
subjects_without_faculty = []

for subject in attendance_df["Subject"].unique():
    if subject not in faculty_df["Subject"].unique():
        subjects_without_faculty.append(subject)

print(subjects_without_faculty)

[]

In [82]:
all_course_subjects = list(set(
    subject
    for subject_list in courses_by_program.values()
    for subject in subject_list
))

print(len(all_course_subjects))
print(all_course_subjects)

25
['Business Analytics', 'Strategic Management', 'Taxation', 'Corporate Accounting', 'Web Development', 'Principles of Management', 'Business Economics', 'Marketing Management', 'Database Management', 'Human Resource Management', 'Data Structures', 'Business Law', 'Business Research', 'Corporate Finance', 'Advanced Accounting', 'Business Communication', 'Income Tax', 'Advanced Economics', 'Operations Management', 'Financial Accounting', 'Cost Accounting', 'Computer Networks', 'Financial Management', 'Programming Fundamentals', 'Operating Systems']

In [83]:
for i in range(len(faculty_df)):
    faculty_df.loc[i, "Subject"] = all_course_subjects[i % len(all_course_subjects)]

In [84]:
missing_subjects = set(all_course_subjects) - set(faculty_df["Subject"])

print("Subjects without faculty:", missing_subjects)

Subjects without faculty: set()

In [85]:
print("Attendance shape:", attendance_df.shape)
print("Missing Faculty IDs:", attendance_df["Faculty_Id"].isna().sum())

Attendance shape: (3000, 11)
Missing Faculty IDs: 0

In [86]:
attendance_df[
    attendance_df["Faculty_Id"].isna()
]["Subject"].value_counts()

Series([], Name: count, dtype: int64)

In [87]:
faculty_df[
    faculty_df["Subject"] == "Principles of Management"
][["faculty_Id", "Department", "Subject"]]

   faculty_Id        Department                   Subject
5      FAC006          Commerce  Principles of Management
30     FAC031          Commerce  Principles of Management
55     FAC056  Computer Science  Principles of Management
80     FAC081  Computer Science  Principles of Management

In [88]:
print(
    len(
        faculty_df[
            faculty_df["Subject"] == "Principles of Management"
        ]
    )
)

4

In [89]:
subject_faculty_map = (
    faculty_df
    .drop_duplicates(subset=["Subject"])
    .set_index("Subject")["faculty_Id"]
    .to_dict()
)

In [90]:
attendance_df["Faculty_Id"] = attendance_df["Subject"].map(subject_faculty_map)

In [91]:
faculty_subject_check = attendance_df.merge(
    faculty_df[["faculty_Id", "Subject"]],
    left_on=["Faculty_Id", "Subject"],
    right_on=["faculty_Id", "Subject"],
    how="left"
)

print(
    "Invalid Faculty-Subject Records:",
    faculty_subject_check["faculty_Id"].isna().sum()
)

Invalid Faculty-Subject Records: 0

In [92]:
print("Attendance Shape:", attendance_df.shape)

print(
    "Missing Faculty IDs:",
    attendance_df["Faculty_Id"].isna().sum()
)

print(
    "Invalid Student IDs:",
    (~attendance_df["Student_ID"].isin(student_df["Student_ID"])).sum()
)

print(
    "Students:",
    attendance_df["Student_ID"].nunique()
)

print(
    "Attendance records per student:"
)

print(
    attendance_df.groupby("Student_ID")["Subject"]
    .nunique()
    .value_counts()
)

Attendance Shape: (3000, 11)
Missing Faculty IDs: 0
Invalid Student IDs: 0
Students: 500
Attendance records per student:
Subject
6    500
Name: count, dtype: int64

In [93]:
##Data Type

datasets = {
    "Student": student_df,
    "Faculty": faculty_df,
    "Course": course_df,
    "Attendance": attendance_df,
    "Issue": issue_df,
    "Assignment": assignment_df,
    "Exam_Result": exam_result_df,
    "Final_Result": student_final_result_df,
    "Feedback": student_feedback_df
}

for name, df in datasets.items():
    print(f"\n{name}")
    print(df.dtypes)

Student
Student_ID                  str
Student_Name                str
Gender                      str
Age                       int64
City                        str
Program                     str
Batch                       str
Semester                  int64
Enrollment_Date          object
Fee_status                  str
Attendance                int64
Assignment_Submission     int64
Course_Completion         int64
Risk_level                  str
dtype: object

Faculty
faculty_Id              str
faculty_name            str
Gender                  str
Age                   int64
Email                   str
Phone_Number            str
Department              str
Subject                 str
Qualification           str
Experience_Years      int64
Joining_Date         object
Employment_Type         str
Faculty_Rating      float64
City                    str
dtype: object

Course
Course_ID                   str
Program                     str
Course_Name                 str
Department                  str
Semester                  int64
Credits                   int64
Course_Type                 str
Faculty_ID                  str
Course_Duration_Months    int64
dtype: object

Attendance
Attendance_Id                str
Student_ID                   str
Program                      str
Semester                   int64
Subject                      str
Faculty_Id                   str
Classes_Conducted          int64
Classes_Attended           int64
Attendance_Percentage    float64
Attendance_Status            str
Attendance_Risk              str
dtype: object

Issue
Issue_Id                   str
Student_ID                 str
Program                    str
Semester                 int64
Issue_Date              object
Issue_Category             str
Issue_Description          str
Priority                   str
Assigned_Team              str
Ticket_Status              str
Resolution_Date         object
Resolution_TAT_Days    float64
SLA_Status                 str
dtype: object

Assignment
Assignment_Id          str
Student_ID             str
Program                str
Semester             int64
Subject                str
Assignment_Status      str
dtype: object

Exam_Result
Exam_Result_ID      str
Student_ID          str
Program             str
Semester          int64
Subject             str
Marks             int64
Grade               str
Result_Status       str
dtype: object

Final_Result
Student_ID           str
Program              str
Semester           int64
Total_Marks        int64
Average_Marks    float64
Final_Grade          str
Final_Result         str
dtype: object

Feedback
Feedback_ID            str
Student_ID             str
Program                str
Semester             int64
Feedback_Category      str
Rating               int64
Feedback_Comments      str
dtype: object

In [94]:
# Convert date columns to proper datetime format

student_df["Enrollment_Date"] = pd.to_datetime(
    student_df["Enrollment_Date"]
)

faculty_df["Joining_Date"] = pd.to_datetime(
    faculty_df["Joining_Date"]
)

issue_df["Issue_Date"] = pd.to_datetime(
    issue_df["Issue_Date"]
)

issue_df["Resolution_Date"] = pd.to_datetime(
    issue_df["Resolution_Date"],
    errors="coerce"
)

print("Enrollment Date:", student_df["Enrollment_Date"].dtype)
print("Joining Date:", faculty_df["Joining_Date"].dtype)
print("Issue Date:", issue_df["Issue_Date"].dtype)
print("Resolution Date:", issue_df["Resolution_Date"].dtype)

Enrollment Date: datetime64[s]
Joining Date: datetime64[s]
Issue Date: datetime64[s]
Resolution Date: datetime64[s]

In [95]:
print("=== FINAL DATA CLEANING CHECK ===")

print("\nStudent duplicates:",
      student_df["Student_ID"].duplicated().sum())

print("Faculty duplicates:",
      faculty_df["faculty_Id"].duplicated().sum())

print("Course duplicates:",
      course_df["Course_ID"].duplicated().sum())

print("Attendance duplicates:",
      attendance_df["Attendance_Id"].duplicated().sum())

print("Issue duplicates:",
      issue_df["Issue_Id"].duplicated().sum())

print("Assignment duplicates:",
      assignment_df["Assignment_Id"].duplicated().sum())

print("Exam Result duplicates:",
      exam_result_df["Exam_Result_ID"].duplicated().sum())

print("Final Result duplicate students:",
      student_final_result_df["Student_ID"].duplicated().sum())

print("Feedback duplicates:",
      student_feedback_df["Feedback_ID"].duplicated().sum())

=== FINAL DATA CLEANING CHECK ===

Student duplicates: 0
Faculty duplicates: 0
Course duplicates: 0
Attendance duplicates: 0
Issue duplicates: 0
Assignment duplicates: 0
Exam Result duplicates: 0
Final Result duplicate students: 0
Feedback duplicates: 0

In [98]:
student_final_result_df["Final_Result"].value_counts()

Final_Result
Pass    350
Fail    150
Name: count, dtype: int64

In [99]:
student_final_result_df["Final_Result"].value_counts(normalize=True) * 100

Final_Result
Pass    70.0
Fail    30.0
Name: proportion, dtype: float64